### ISSUE TITLE
java.lang.IllegalArgumentException and java.lang.NullPointerException

### ISSUE THREAD

**Issue by lynxjr3** [quat1024/modern-forge-1.12-template#3]
When i try to start the game by doing runClient it gives java.lang.IllegalArgumentException and java.lang.NullPointerException so it would be great if someone could help.

**Comment by mpfaff** [comment]
It appears that some dependencies are being pulled in that are compiled for a newer version of Java than Java 8.

**Comment by PopSoda404** [comment]
Im having the same issue. Can you at least tell me a possible solution since every template does the same thing?

**Comment by quat1024** [comment]
dupe #2
