### ISSUE TITLE
`FAILURE: Build failed with an exception.`

### ISSUE THREAD

**Issue by QazCetelic** [quat1024/modern-forge-1.12-template#4]
Running `./gradlew build` results in the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'modern-forge-1.12-template'.
> Could not open cp_proj generic class cache for build file '/home/user/Programming/MCO/modern-forge-1.12-template/build.gradle' (/home/user/.gradle/caches/7.6.1/scripts/5bau75o2n3zlohboj9l54mafu).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 486ms
```

I have tested it with both Java 8 and 21

**Comment by QazCetelic** [comment]
It turns out it was caused by the Java version I used. I changed the system wide default, but `./gradlew` apparently ignores the system default Java version and instead seems to pick the latest version (which was 21) unless manually overridden with `-Dorg.gradle.java.home`.

If anyone else is having this:
1. Ensure you have Java 11 installed.
2. Locate Java 11 install location (probably `/usr/lib64/jvm/jre-11-openjdk/` if you're on Linux)
3. Call the gradle script like so: `./gradlew <GRADLE_TASK> -Dorg.gradle.java.home=<JAVA_HOME>`
   - <GRADLE_TASK> is the task to be run here (e.g. `build`).
   - <JAVA_HOME> is the directory of the Java install, make sure to not include `/bin/java`

**Comment by quat1024** [comment]
The Gradle wrapper script should *(should!)* respect the `JAVA_HOME` environment variable:

https://github.com/quat1024/modern-forge-1.12-template/blob/344ade81f736f19ca9a7c85e17752342ed37e3c7/gradlew#L120-L121

In my shell I set up `JAVA8`, `JAVA17` etc environment variables so I can go `JAVA_HOME=$JAVA8 ./gradlew ...`

**Comment by QazCetelic** [comment]
`update-alternatives` only updates the binary the default java symlink points to. This updates the version shown when running `java -version`, but does not change the environment variable :shrug:. Anyway, thanks for creating this template.
